# Generated by Django 4.1.6 on 2023-02-14 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_technicalimage_specificationimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/channel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=200, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='assembly_archive',
            field=models.FileField(blank=True, null=True, upload_to='assembly_archive_path'),
        ),
        migrations.AddField(
            model_name='product',
            name='assembly_pdf',
            field=models.FileField(blank=True, null=True, upload_to='assembly_pdf_path'),
        ),
        migrations.AddField(
            model_name='product',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='drawing_3d_3dmax',
            field=models.FileField(blank=True, null=True, upload_to='drawing_3d_3dmax_path'),
        ),
        migrations.AddField(
            model_name='product',
            name='drawing_3d_dwg',
            field=models.FileField(blank=True, null=True, upload_to='drawing_3d_dwg_path'),
        ),
        migrations.AddField(
            model_name='product',
            name='drawing_3d_obj',
            field=models.FileField(blank=True, null=True, upload_to='drawing_3d_obj_path'),
        ),
        migrations.AddField(
            model_name='product',
            name='drawing_3d_sketchup',
            field=models.FileField(blank=True, null=True, upload_to='drawing_3d_sketchup_path'),
        ),
        migrations.AddField(
            model_name='product',
            name='moq',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='prefix_code',
            field=models.CharField(blank=True, choices=[('LC', 'Lounge Chair'), ('LS', 'Love Seat'), ('SO', 'Sofa'), ('LO', 'Lounge Stool'), ('CT', 'Coffe Table'), ('ST', 'Side Table'), ('OT', 'Ottoman'), ('DC', 'Dining Chair'), ('SC', 'Side Chair'), ('LG', 'Lounger'), ('DT', 'Dining Table'), ('BN', 'Bench'), ('PN', 'Panel'), ('BT', 'Bar Table'), ('BS', 'Bar Stool'), ('BC', 'Bar Chair'), ('MR', 'Modular Right'), ('ML', 'Modular Left'), ('MM', 'Modular Middle'), ('MC', 'Modular Corner'), ('NT', 'Console Table'), ('BO', 'Bathroom Stool'), ('BB', 'Bathroom Bench'), ('SS', 'Shaving Stool'), ('SF', 'Shelf'), ('BK', 'Basket'), ('TY', 'Tray'), ('TS', 'Towel Stand'), ('MT', 'Mat'), ('CB', 'Cabana'), ('PR', 'Parasol'), ('SD', 'Base Stand'), ('PL', 'Planter'), ('LT', 'Lantern'), ('TP', 'Throw Pillow'), ('PF', 'Pouf'), ('NO', 'None')], default='NO', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='production_drawing_archive',
            field=models.FileField(blank=True, null=True, upload_to='production_drawing_archive_path'),
        ),
        migrations.AddField(
            model_name='product',
            name='production_drawing_pdf',
            field=models.FileField(blank=True, null=True, upload_to='production_drawing_pdf_path'),
        ),
        migrations.AddField(
            model_name='product',
            name='ps_20ft_container',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ps_40gp_container',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ps_40hq_container',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ps_arm_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ps_box_dimension',
            field=models.CharField(blank=True, help_text='74,48,20', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='ps_box_weight',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ps_gross_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ps_nett_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ps_overal_dimension',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ps_pax',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ps_product_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ps_seat_construction',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ps_seat_depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ps_seat_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_meta_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_meta_keyword',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_meta_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='bom_file',
            field=models.FileField(blank=True, null=True, upload_to='bom_file_path'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='product_pro_created_22b186_idx'),
        ),
        migrations.AddField(
            model_name='product',
            name='channel',
            field=models.ManyToManyField(blank=True, to='product.channel'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ManyToManyField(blank=True, to='product.material'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_product', to='product.unit'),
        ),
    ]
